# Generated by Django 4.2.1 on 2023-05-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coustemers',
            new_name='Coustomers',
        ),
    ]
