# Generated by Django 4.2.1 on 2023-05-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customersaddress_rename_coustomers_customers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersaddress',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customersaddress',
            name='street_number',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='CustomersAadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_number', models.IntegerField(blank=True, max_length=15, null=True)),
                ('aadhar_name', models.CharField(blank=True, max_length=15, null=True)),
                ('customers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
            ],
        ),
    ]
