# Generated by Django 4.2.1 on 2023-05-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customersaddress_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersaddress',
            name='customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='customer.customers'),
        ),
    ]
